<?php

if( function_exists('acf_add_local_field_group') ):

acf_add_local_field_group(array (
	'key' => 'group_56f32404ba5e5',
	'title' => 'Embedded media',
	'fields' => array (
		array (
			'key' => 'field_56f3240b3c411',
			'label' => 'Enter the url for the media you want to add',
			'name' => 'tome_media_embed_script',
			'type' => 'textarea',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'maxlength' => '',
			'rows' => '',
			'new_lines' => 'wpautop',
			'readonly' => 0,
			'disabled' => 0,
		)
	),
	'location' => array (
		array (
			array (
				'param' => 'post_type',
				'operator' => '==',
				'value' => 'tome_media',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'normal',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
));


// cover settings
acf_add_local_field_group(array (
	'key' => 'group_57191ce1e0ec1',
	'title' => 'Cover Settings',
	'fields' => array (
		array (
			'key' => 'field_571920fc6724d',
			'label' => 'Content',
			'name' => '',
			'type' => 'tab',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'placement' => 'top',
		),
		array (
			'key' => 'field_57191ce973179',
			'label' => 'Book Title',
			'name' => 'book_title',
			'type' => 'text',
			'instructions' => 'Your Book Title',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => 'Your Book Title',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
			'readonly' => 0,
			'disabled' => 0,
		),
		array (
			'key' => 'field_57da9fbd26de6',
			'label' => 'Book Author',
			'name' => 'book_author',
			'type' => 'text',
			'instructions' => 'Author of the book',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => 'John Doe',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
			'readonly' => 0,
			'disabled' => 0,
		),
		array (
			'key' => 'field_5722605ad7ca2',
			'label' => 'Button Link',
			'name' => 'button_link',
			'type' => 'post_object',
			'instructions' => 'Link to the chapter or page, you have already created.',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'post_type' => array (
				0 => 'chapter',
				1 => 'page',
			),
			'taxonomy' => array (
			),
			'allow_null' => 0,
			'multiple' => 0,
			'return_format' => 'id',
			'ui' => 1,
		),
		array (
			'key' => 'field_57191ded8ddb6',
			'label' => 'Book Subtitle/Description',
			'name' => 'book_description',
			'type' => 'wysiwyg',
			'instructions' => 'Describe what is your book about.',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => 'Additional text you’d like to appear here, or just delete this if you don’t want any more text here.',
			'tabs' => 'all',
			'toolbar' => 'full',
			'media_upload' => 0,
		),
		array (
			'key' => 'field_5719212a6724e',
			'label' => 'Styling',
			'name' => '',
			'type' => 'tab',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'placement' => 'top',
		),
		array (
			'key' => 'field_5739ab33ea138',
			'label' => 'Content Background Color',
			'name' => 'content_background_color',
			'type' => 'color_picker',
			'instructions' => 'Background from the content.',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '#000000',
		),
		array (
			'key' => 'field_5739ab7eea139',
			'label' => 'Content Background Opacity',
			'name' => 'content_background_opacity',
			'type' => 'number',
			'instructions' => 'Background from the content.',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => 1,
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'min' => 0,
			'max' => 1,
			'step' => '0.1',
			'readonly' => 0,
			'disabled' => 0,
		),
		array (
			'key' => 'field_5719201f59378',
			'label' => 'Title Color',
			'name' => 'title_color',
			'type' => 'color_picker',
			'instructions' => 'Book Title Color',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '#fff',
		),
		array (
			'key' => 'field_571920915937b',
			'label' => 'Book Description Text Color',
			'name' => 'book_description_color',
			'type' => 'color_picker',
			'instructions' => 'Book Description Text Color',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '#fff',
		),
		array (
			'key' => 'field_571923aa22817',
			'label' => 'Layout',
			'name' => '',
			'type' => 'tab',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'placement' => 'top',
		),
		array (
			'key' => 'field_571923b822818',
			'label' => 'Content Position',
			'name' => 'content_position',
			'type' => 'select',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'choices' => array (
				'center' => 'Centered',
				'top' => 'Top Half',
				'bottom' => 'Bottom Half',
			),
			'default_value' => array (
				'top' => 'Top Side',
			),
			'allow_null' => 0,
			'multiple' => 0,
			'ui' => 0,
			'ajax' => 0,
			'placeholder' => '',
			'disabled' => 0,
			'readonly' => 0,
		),
		array (
			'key' => 'field_571a5df7bacef',
			'label' => 'Background Style',
			'name' => '',
			'type' => 'tab',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'placement' => 'top',
		),
		array (
			'key' => 'field_571a5e07bacf0',
			'label' => 'Background type',
			'name' => 'background_type',
			'type' => 'select',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'choices' => array (
				'image' => 'Image',
				'rand_img' => 'Choose multiple images',
				'video_loop' => 'Use a video loop',
				'external_media' => 'Use external video as the cover',
			),
			'default_value' => array (
				'image' => 'Image',
			),
			'allow_null' => 0,
			'multiple' => 0,
			'ui' => 1,
			'ajax' => 0,
			'placeholder' => '',
			'disabled' => 0,
			'readonly' => 0,
		),
		array (
			'key' => 'field_571a6e2144fbc',
			'label' => 'Custom Background Image',
			'name' => 'custom_background_image',
			'type' => 'image',
			'instructions' => 'Upload your custom image for a cover page background.',
			'required' => 0,
			'conditional_logic' => array (
				array (
					array (
						'field' => 'field_571a5e07bacf0',
						'operator' => '==',
						'value' => 'image',
					),
				),
			),
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'return_format' => 'url',
			'preview_size' => 'thumbnail',
			'library' => 'all',
			'min_width' => '',
			'min_height' => '',
			'min_size' => '',
			'max_width' => '',
			'max_height' => '',
			'max_size' => '',
			'mime_types' => 'jpg, png, jpeg',
		),
		array (
			'key' => 'field_571a6ff6e7821',
			'label' => 'Video Background (webm)',
			'name' => 'video_background_webm',
			'type' => 'file',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => array (
				array (
					array (
						'field' => 'field_571a5e07bacf0',
						'operator' => '==',
						'value' => 'video_loop',
					),
				),
			),
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'return_format' => 'array',
			'library' => 'all',
			'min_size' => '',
			'max_size' => '',
			'mime_types' => '',
		),
		array (
			'key' => 'field_57ead25daeb8a',
			'label' => 'Video Background (mp4)',
			'name' => 'video_background_mp4',
			'type' => 'file',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => array (
				array (
					array (
						'field' => 'field_571a5e07bacf0',
						'operator' => '==',
						'value' => 'video_loop',
					),
				),
			),
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'return_format' => 'array',
			'library' => 'all',
			'min_size' => '',
			'max_size' => '',
			'mime_types' => '',
		),
		array (
			'key' => 'field_571a70e8e7822',
			'label' => 'Video Background (ogv)',
			'name' => 'video_background_ogv',
			'type' => 'file',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => array (
				array (
					array (
						'field' => 'field_571a5e07bacf0',
						'operator' => '==',
						'value' => 'video_loop',
					),
				),
			),
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'return_format' => 'array',
			'library' => 'all',
			'min_size' => '',
			'max_size' => '',
			'mime_types' => '',
		),
		array (
			'key' => 'field_571a7113e7824',
			'label' => 'Fallback Image',
			'name' => 'fallback_image',
			'type' => 'image',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => array (
				array (
					array (
						'field' => 'field_571a5e07bacf0',
						'operator' => '==',
						'value' => 'video_loop',
					),
				),
			),
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'return_format' => 'url',
			'preview_size' => 'thumbnail',
			'library' => 'all',
			'min_width' => '',
			'min_height' => '',
			'min_size' => '',
			'max_width' => '',
			'max_height' => '',
			'max_size' => '',
			'mime_types' => '',
		),
		array (
			'key' => 'field_571eb3a634613',
			'label' => 'Multiple Images Background',
			'name' => 'multiple_images_background',
			'type' => 'gallery',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => array (
				array (
					array (
						'field' => 'field_571a5e07bacf0',
						'operator' => '==',
						'value' => 'rand_img',
					),
				),
			),
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'min' => '',
			'max' => '',
			'preview_size' => 'thumbnail',
			'library' => 'all',
			'min_width' => '',
			'min_height' => '',
			'min_size' => '',
			'max_width' => '',
			'max_height' => '',
			'max_size' => '',
			'mime_types' => 'jpg, jpeg, png, gif',
		),
		array (
			'key' => 'field_580e4ba04da3e',
			'label' => 'Select Embed Media',
			'name' => 'select_external_media',
			'type' => 'oembed',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => array (
				array (
					array (
						'field' => 'field_571a5e07bacf0',
						'operator' => '==',
						'value' => 'external_media',
					),
				),
			),
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'width' => '',
			'height' => '',
		),
	),
	'location' => array (
		array (
			array (
				'param' => 'options_page',
				'operator' => '==',
				'value' => 'tome-cover-settings',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'normal',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
));

acf_add_local_field_group(array (
	'key' => 'group_5447404710661',
	'title' => 'Gallery Contents',
	'fields' => array (
		array (
			'key' => 'field_55a2c1f57d0ac',
			'label' => 'Gallery Cover Photo',
			'name' => 'gallery_cover_photo',
			'type' => 'image',
			'instructions' => 'The cover photo appears in the chapter. Clicking the cover photo will let the reader view the full gallery. For best results, the cover photo should be square.',
			'required' => 1,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'return_format' => 'array',
			'preview_size' => 'thumbnail',
			'library' => 'all',
			'min_width' => '',
			'min_height' => '',
			'min_size' => '',
			'max_width' => '',
			'max_height' => '',
			'max_size' => '',
			'mime_types' => '',
		),
		array (
			'key' => 'field_5447404e5b068',
			'label' => 'Gallery Slide',
			'name' => 'gallery_slide',
			'type' => 'gallery',
			'instructions' => 'Use this to add the items to your gallery.',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'min' => 1,
			'max' => '',
			'preview_size' => 'thumbnail',
			'library' => 'all',
			'min_width' => '',
			'min_height' => '',
			'min_size' => '',
			'max_width' => '',
			'max_height' => '',
			'max_size' => '',
			'mime_types' => '',
		),
	),
	'location' => array (
		array (
			array (
				'param' => 'post_type',
				'operator' => '==',
				'value' => 'tome_gallery',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'acf_after_title',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
));


acf_add_local_field_group(array (
	'key' => 'group_56b96f816afb7',
	'title' => 'Header Options',
	'metabox' => false,
	'fields' => array (
		array (
			'key' => 'field_56b96f8171a92',
			'label' => 'Header Style Options',
			'name' => 'tome_header_style_options',
			'type' => 'select',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'choices' => array (
				'none' => 'None',
				'featured_img' => 'Image',
				'embed' => 'Use External Media',
				'video_loop' => 'Use a video loop',
				'place' => 'Use a Place',
				'map' => 'Use a Map',
			),
			'default_value' => array (
				'none' => 'None',
			),
			'allow_null' => 0,
			'multiple' => 0,
			'ui' => 1,
			'ajax' => 0,
			'placeholder' => '',
			'disabled' => 0,
			'readonly' => 0,
		),
		array (
			'key' => 'field_56b96f8171acb',
			'label' => 'Video Background (webm)',
			'name' => 'tome_header_video_bg_webm',
			'type' => 'file',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => array (
				array (
					array (
						'field' => 'field_56b96f8171a92',
						'operator' => '==',
						'value' => 'video_loop',
					),
				),
			),
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'return_format' => 'url',
			'library' => 'all',
			'min_size' => '',
			'max_size' => '',
			'mime_types' => '',
		),
		array (
			'key' => 'field_56b96f8171ae7',
			'label' => 'Video Background (ogv)',
			'name' => 'tome_header_video_bg_ogv',
			'type' => 'file',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => array (
				array (
					array (
						'field' => 'field_56b96f8171a92',
						'operator' => '==',
						'value' => 'video_loop',
					),
				),
			),
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'return_format' => 'url',
			'library' => 'all',
			'min_size' => '',
			'max_size' => '',
			'mime_types' => '',
		),
		array (
			'key' => 'field_56b96f8171b02',
			'label' => 'Fallback Image',
			'name' => 'tome_header_fallback_image',
			'type' => 'image',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => array (
				array (
					array (
						'field' => 'field_56b96f8171a92',
						'operator' => '==',
						'value' => 'video_loop',
					),
				),
			),
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'return_format' => 'array',
			'preview_size' => 'thumbnail',
			'library' => 'all',
			'min_width' => '',
			'min_height' => '',
			'min_size' => '',
			'max_width' => '',
			'max_height' => '',
			'max_size' => '',
			'mime_types' => '',
		),
		array (
			'key' => 'field_56b97336b4f2c',
			'label' => 'Place',
			'name' => 'tome_header_place',
			'type' => 'post_object',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => array (
				array (
					array (
						'field' => 'field_56b96f8171a92',
						'operator' => '==',
						'value' => 'place',
					),
				),
			),
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'post_type' => array (
				0 => 'tome_place',
			),
			'taxonomy' => array (
			),
			'allow_null' => 1,
			'multiple' => 0,
			'return_format' => 'id',
			'ui' => 1,
		),
		array (
			'key' => 'field_58dd230cbed91',
			'label' => 'Map',
			'name' => 'tome_header_map',
			'type' => 'post_object',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => array (
				array (
					array (
						'field' => 'field_56b96f8171a92',
						'operator' => '==',
						'value' => 'map',
					),
				),
			),
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'post_type' => array (
				0 => 'tome_map',
			),
			'taxonomy' => array (
			),
			'allow_null' => 1,
			'multiple' => 0,
			'return_format' => 'id',
			'ui' => 1,
		),
		array (
			'key' => 'field_572277d20c6f6',
			'label' => 'header_image',
			'name' => 'header_image',
			'type' => 'image',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => array (
				array (
					array (
						'field' => 'field_56b96f8171a92',
						'operator' => '==',
						'value' => 'featured_img',
					),
				),
			),
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'return_format' => 'array',
			'preview_size' => 'thumbnail',
			'library' => 'all',
			'min_width' => '',
			'min_height' => '',
			'min_size' => '',
			'max_width' => '',
			'max_height' => '',
			'max_size' => '',
			'mime_types' => '',
		),
		array (
			'key' => 'field_56b973aeb4f2d',
			'label' => 'External Media',
			'name' => 'tome_header_embed',
			'type' => 'post_object',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => array (
				array (
					array (
						'field' => 'field_56b96f8171a92',
						'operator' => '==',
						'value' => 'embed',
					),
				),
			),
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'post_type' => array (
				0 => 'tome_external_media',
			),
			'taxonomy' => array (
			),
			'allow_null' => 1,
			'multiple' => 0,
			'return_format' => 'id',
			'ui' => 1,
		),
		array (
			'key' => 'field_56ccac4b11928',
			'label' => 'Show Caption',
			'name' => 'tome_header_show_caption',
			'type' => 'true_false',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => array (
				array (
					array (
						'field' => 'field_56b96f8171a92',
						'operator' => '==',
						'value' => 'featured_img',
					),
				),
				array (
					array (
						'field' => 'field_56b96f8171a92',
						'operator' => '==',
						'value' => 'embed',
					),
				),
				array (
					array (
						'field' => 'field_56b96f8171a92',
						'operator' => '==',
						'value' => 'video_loop',
					),
				),
			),
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'message' => '',
			'default_value' => 0,
		),
		array (
			'key' => 'field_56ccac981192b',
			'label' => 'Caption Text',
			'name' => 'tome_header_caption_text',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => array (
				array (
					array (
						'field' => 'field_56ccac4b11928',
						'operator' => '==',
						'value' => '1',
					),
				),
			),
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
			'readonly' => 0,
			'disabled' => 0,
		),
	),
	'location' => array (
		array (
			array (
				'param' => 'post_type',
				'operator' => '==',
				'value' => 'chapter',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'normal',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
));


acf_add_local_field_group(array (
	'key' => 'group_54593dc0e7b4f',
	'title' => 'Tome Map Fields',
	'fields' => array (
		array (
			'key' => 'field_54593ddcc6da5',
			'label' => 'Places',
			'name' => 'places',
			'type' => 'repeater',
			'instructions' => 'Choose the places you would like to add to your map.',
			'required' => 1,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'min' => '',
			'max' => '',
			'layout' => 'table',
			'button_label' => 'Add Place',
			'sub_fields' => array (
				array (
					'key' => 'field_54593e29c6da6',
					'label' => 'Place',
					'name' => 'place',
					'type' => 'post_object',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array (
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'post_type' => array (
						0 => 'tome_place',
					),
					'taxonomy' => array (
					),
					'allow_null' => 0,
					'multiple' => 0,
					'return_format' => 'object',
					'ui' => 1,
				),
			),
		),
	),
	'location' => array (
		array (
			array (
				'param' => 'post_type',
				'operator' => '==',
				'value' => 'tome_map',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'normal',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
));

endif;

?>